# tensor初始化、数学操作等

## 初始化
   

### torch.tensor()

使用`torch.tensor()`将numpy或者list等转换为tensor

In [1]:
import torch
import numpy as np
my_tensor=torch.tensor(np.ones(3))
print(my_tensor)

tensor([0., 0., 0.], dtype=torch.float64)


In [4]:
my_tensor=torch.tensor([1,2,3])
my_tensor

tensor([1, 2, 3])

使用多维list初始化多维tensor,例如下述代码初始化一个两行三列的tensor

In [36]:
my_tensor=torch.tensor([[1,2,3],[4, 5, 6]])
print(my_tenosr)
print(my_tenosr.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


通过`dtype`字段指定数据类型，`dtype`可选`torch.float32`, `torch.float64`, `torch.float16`, `torch.int8`, `torch.int16`, `torch.int32`等

例如

In [15]:
my_tensor=torch.tensor([[1,2,3],[4, 5, 6]],dtype=torch.float64)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [18]:
my_tensor=torch.tensor([[1,2,3],[4, 5, 6]],dtype=torch.float32)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [17]:
my_tensor=torch.tensor([[1,2,3],[4, 5, 6]],dtype=torch.int32)
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

通过`device`字段指定将tensor分配分配给哪个设备（cpu或则gpu）。具体来说，`torch.device`代表将`torch.Tensor`分配到的设备的对象。`torch.device`包含一个设备类型（‘cpu’或‘cuda’）和可选的设备序号。如果设备序号不存在，则为当前设备。如：`torch.Tensor`用设备构建`'cuda'`的结果等同于`‘cuda：X’`，其中X是`torch.cuda.current_device()`的结果。

In [23]:
my_tensor=torch.tensor([[1,2,3],[4, 5, 6]],dtype=torch.int32,device='cpu')
print(my_tensor.device)

cpu


可以使用如下代码，优先将tensor分配给GPU

In [25]:
mydevice='cuda' if torch.cuda.is_available() else 'cpu'
print(mydevice)

cpu


In [30]:
my_tensor=torch.tensor([1,2,3],device=mydevice)
print(my_tensor.device)
print(my_tensor.dtype)

cpu
torch.int64


通过字段'requires_grad'来指定tensor是否需要进行求导（反向传播），默认情况下该字段为`False`

In [38]:
print(my_tensor.requires_grad)

False


In [39]:
my_tensor=torch.tensor([1.5,2,3],requires_grad=True)
print(my_tensor.requires_grad)

True


如果想改变`requires_grad`这个属性，可以调用`tensor.requires_grad_()`方法：
```
x.requires_grad_(True)
```

In [40]:
my_tensor=torch.tensor([1.5,2,3])
print(my_tensor.requires_grad)
my_tensor.requires_grad_(True)
print(my_tensor.requires_grad)

False
True


### 填充指定size的tensor
1. torch.empty()  
2. torch.ones()
3. torch.zeros()  
4. torch.eye()

#### 1. torch.empty()

使用`torch.empty()`可以创建包含未初始化数据的张量
标量值0填充的张量,其形状由变量参数size定义

In [47]:
my_tensor=torch.empty((3,4))
print(my_tensor.shape)
print(my_tensor)#具体值实际上待定，不要以为是初始化为0

torch.Size([3, 4])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
#### 2. torch.zeros()

In [70]:
my_tensor=torch.zeros(3,4)
print(my_tensor.shape)
print(my_tensor)

torch.Size([3, 4])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


#### 3. torch.ones()

In [69]:
my_tensor=torch.ones(3,4,5)
print(my_tensor.shape)
print(my_tensor)

torch.Size([3, 4, 5])
tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])


#### 4. torch.eye()  
生成对角线全1，其余部分全0的二维数组

In [63]:
my_tensor=torch.eye(3)
print(my_tensor.shape)
print(my_tensor)

torch.Size([3, 3])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [64]:
my_tensor=torch.eye(2,3)
print(my_tensor.shape)
print(my_tensor)

torch.Size([2, 3])
tensor([[1., 0., 0.],
        [0., 1., 0.]])


#### 4. torch.rand()  
包含了从区间[0, 1)的均匀分布中抽取的一组随机数

In [68]:
my_tensor=torch.rand(3,4)
print(my_tensor.shape)
print(my_tensor)

torch.Size([3, 4])
tensor([[0.4518, 0.6142, 0.7612, 0.3828],
        [0.6862, 0.0493, 0.5492, 0.2327],
        [0.7688, 0.1837, 0.6124, 0.3847]])


#### 4. torch.randn()  
包含了从**标准正态分布**中抽取的一组随机数

In [67]:
my_tensor=torch.randn(3,4)
print(my_tensor.shape)
print(my_tensor)

torch.Size([3, 4])
tensor([[ 0.0647, -0.1434,  2.0323, -0.2759],
        [-0.9258,  0.3505, -0.7455, -0.0367],
        [ 0.6792,  0.5661,  1.5247, -1.3066]])


#### torch.arange( start, end, step)：不含end (建议使用)
#### torch.range( start, end, step): 含end (不建议使用，后续可能会被移除)

In [82]:
my_tensor = torch.arange(start=0, end=5, step=1)  
print(my_tensor.shape)
print(my_tensor)
my_tensor = torch.range(start=0, end=5, step=1)  
print(my_tensor.shape)
print(my_tensor)

torch.Size([5])
tensor([0, 1, 2, 3, 4])
torch.Size([6])
tensor([0., 1., 2., 3., 4., 5.])


<ipython-input-82-c200653eb586>:4: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  my_tensor = torch.range(start=0, end=5, step=1)


也可以不用加start和end关键字，按参数次序写即可

In [88]:
my_tensor = torch.arange(0,5,2)  
print(my_tensor.shape)
print(my_tensor)
my_tensor = torch.range(0,5,2)  
print(my_tensor.shape)
print(my_tensor)

torch.Size([3])
tensor([0, 2, 4])
torch.Size([3])
tensor([0., 2., 4.])


<ipython-input-88-1464d512cadc>:4: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  my_tensor = torch.range(0,5,2)


step参数默认为1

In [84]:
my_tensor = torch.arange(0,5)  
print(my_tensor.shape)
print(my_tensor)
my_tensor = torch.range(0,5) #注意，结果中包含end 
print(my_tensor.shape)
print(my_tensor)

torch.Size([5])
tensor([0, 1, 2, 3, 4])
torch.Size([6])
tensor([0., 1., 2., 3., 4., 5.])


<ipython-input-84-5b1a9771b9c9>:4: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  my_tensor = torch.range(0,5)


也可以只传入end参数，此时默认start为0

In [80]:
my_tensor = torch.arange( ,11,2)  
print(my_tensor.shape)
print(my_tensor)

SyntaxError: invalid syntax (<ipython-input-80-15233ef67f78>, line 1)

In [87]:
my_tensor = torch.arange(5)  
print(my_tensor.shape)
print(my_tensor)
my_tensor = torch.range(0,5)  
print(my_tensor.shape)
print(my_tensor)

torch.Size([5])
tensor([0, 1, 2, 3, 4])
torch.Size([6])
tensor([0., 1., 2., 3., 4., 5.])


<ipython-input-87-1bff08bca9ba>:4: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  my_tensor = torch.range(0,5)


In [ ]:
x = torch.linspace(start=0.1, end=1, steps=10)  # x = [0.1, 0.2, ..., 1]

#### torch.linspace(start, end, steps)
`torch.linspace`同`torch.range`均是左闭右闭，即返回值中既包含start也包含end. 但是不同之处在于，`torch.linspace`中的steps参数应该理解为元素总个数，而`torch.range`中的step参数应该理解为步长（前后元素之间的差）
这个张量包含了从start到end（包括端点）的等距的steps个数据点

In [89]:
my_tensor = torch.range(0,5,2)  
print(my_tensor.shape)
print(my_tensor)
my_tensor = torch.linspace(0,5,2)  
print(my_tensor.shape)
print(my_tensor)

torch.Size([3])
tensor([0., 2., 4.])
torch.Size([2])
tensor([0., 5.])


<ipython-input-89-1f46291fd614>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  my_tensor = torch.range(0,5,2)


#### torch.diag(input, diagonal=0, out=None) → Tensor
如果输入是一个向量(1D 张量)，则返回一个以input为对角线元素的2D方阵
如果输入是一个矩阵(2D 张量)，则返回一个包含input对角线元素的1D张量

参数diagonal指定对角线:
diagonal = 0, 主对角线
diagonal > 0, 主对角线之上
diagonal < 0, 主对角线之下
————————————————

In [93]:
my_tensor = torch.ones(3,3)
print(torch.diag(my_tensor))#主对角线
print(torch.diag(my_tensor).shape)

tensor([1., 1., 1.])
torch.Size([3])


In [94]:
print(torch.diag(my_tensor,1)) #主对角线之上的第一条对角线
print(torch.diag(my_tensor).shape)

tensor([1., 1.])
torch.Size([3])


In [95]:
print(torch.diag(my_tensor,2)) #主对角线之上的第二条对角线
print(torch.diag(my_tensor).shape)

tensor([])
torch.Size([3])


In [96]:
print(torch.diag(my_tensor,-2)) #主对角线之下的第二条对角线
print(torch.diag(my_tensor).shape)

tensor([1.])
torch.Size([3])


In [97]:
print(torch.diag(my_tensor,3)) #主对角线之上的第三条对角线（无元素）
print(torch.diag(my_tensor).shape)

tensor([])
torch.Size([3])


转换数值类型(int, float, double)等

In [105]:
my_tensor = torch.tensor([-2,-1,0,1,2])
my_tensor

tensor([-2, -1,  0,  1,  2])

转换为布尔类型（将非0值转为True）

In [108]:
print(f"Converted Boolean: {my_tensor.bool()}")  # Converted to Boolean: 1 if nonzero


Converted Boolean: tensor([ True,  True, False,  True,  True])
Converted int16 tensor([-2, -1,  0,  1,  2], dtype=torch.int16)
Converted int64 tensor([-2, -1,  0,  1,  2])
Converted float16 tensor([-2., -1.,  0.,  1.,  2.], dtype=torch.float16)
Converted float32 tensor([-2., -1.,  0.,  1.,  2.])
Converted float64 tensor([-2., -1.,  0.,  1.,  2.], dtype=torch.float64)


转换为int16

In [109]:
print(f"Converted int16 {my_tensor.short()}")  # Converted to int16

Converted int16 tensor([-2, -1,  0,  1,  2], dtype=torch.int16)


转换为int64

In [110]:
print(
    f"Converted int64 {my_tensor.long()}"
)  # Converted to int64 (This one is very important, used super often)

Converted int64 tensor([-2, -1,  0,  1,  2])


转换为float16

In [111]:
print(f"Converted float16 {my_tensor.half()}")  # Converted to float16


Converted float16 tensor([-2., -1.,  0.,  1.,  2.], dtype=torch.float16)


转换为float32

In [112]:
print(
    f"Converted float32 {my_tensor.float()}"
)  # Converted to float32 (This one is very important, used super often)


Converted float32 tensor([-2., -1.,  0.,  1.,  2.])


转换为float64

In [113]:
print(f"Converted float64 {my_tensor.double()}")  # Converted to float64

Converted float64 tensor([-2., -1.,  0.,  1.,  2.], dtype=torch.float64)


##### torch.from_numpy()与torch.numpy()
前者将numpy类型转换为tensor，后者将tensor转换为numpy类型

In [116]:
np_array = np.zeros((5, 5))
my_tensor = torch.from_numpy(np_array)
np_array_again = (
    my_tensor.numpy()
)  # np_array_again will be same as np_array (perhaps with numerical round offs)
print(my_tensor)
print(np_array_again)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## tensor math
### 加法：torch.add()，+

In [7]:
import torch
x=torch.tensor([1,2,3])
y=torch.tensor([1,1,1])
z=torch.empty(3)
torch.add(x,y,out=z)
print(z)


tensor([2., 3., 4.])


In [8]:
x+y #简介明了，推荐使用

tensor([2, 3, 4])

In [9]:
z1=torch.add(x,y)
print(z1)

tensor([2, 3, 4])


### 减法：torch.sub(),-

In [10]:
x=torch.tensor([1,2,3])
y=torch.tensor([1,1,1])
z=torch.empty(3)
torch.sub(x,y,out=z)
print(z)

tensor([0., 1., 2.])


In [11]:
x-y #简介明了，推荐使用

tensor([0, 1, 2])

### 哈达玛积(element wise，对应元素相乘)：torch.mul(), *

In [12]:
x=torch.tensor([1,2,3])
y=torch.tensor([1,1,1])
z=torch.empty(3)
torch.mul(x,y,out=z)
print(z)

tensor([1., 2., 3.])


In [13]:
x*y

tensor([1, 2, 3])

In [ ]:
哈达玛积运算中，x与y的维度（shape）必须一致。不一致的时候，若符合自动填充机制，则会进行自动填充（Broadcasting机制）

In [20]:
x=torch.tensor([1,2,3])
y=torch.tensor([[1],[1],[1]])
print(x.shape)
print(y.shape)
print((x*y).shape)
print((x*y))

torch.Size([3])
torch.Size([3, 1])
torch.Size([3, 3])
tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])


### 矩阵乘法：
二维矩阵乘法二维矩阵乘法运算操作包括torch.mm()、torch.matmul()

In [23]:
x = torch.ones(2, 1)
y = torch.ones(1, 2)
print(torch.mm(a, b).shape)
print(torch.matmul(a, b).shape)
print((a @ b).shape)

torch.Size([2, 2])
torch.Size([2, 2])
torch.Size([2, 2])


对比二维矩阵中*与@的区别

In [ ]:
x=torch.tensor([1,2,3])
y=torch.tensor([[1],[1],[1]])
print(x.shape)
print(y.shape)
print((x*y).shape)
print((x@y).shape)

对于高维的Tensor（dim>2），定义其矩阵乘法仅在最后的两个维度上(后面部分进行矩阵乘法)，要求前面的维度必须保持一致(前面部分进行哈达玛积)，操只有torch.matmul()

In [31]:
x = torch.rand(2, 3, 4, 5)
y = torch.rand(2, 3, 5, 4)
print(torch.matmul(x, y).shape)
#print(x)
#print(y)
#print(torch.matmul(x, y))

torch.Size([2, 3, 4, 4])


由于前面部分是进行哈达玛积（具有Broadcasting机制），因而高维矩阵相乘时，若前面的"矩阵索引维度"如果符合Broadcasting机制，也会自动做广播，然后相乘。

In [33]:
x = torch.rand(2, 3, 4, 5)
y = torch.rand(2, 1, 5, 4)
print(torch.matmul(x, y).shape)

torch.Size([2, 3, 4, 4])


In [34]:
x = torch.rand(2, 3, 4, 5)
y = torch.rand(1, 3, 5, 4)
print(torch.matmul(x, y).shape)

torch.Size([2, 3, 4, 4])


In [35]:
x = torch.rand(2, 3, 4, 5)
y = torch.rand(3, 5, 4)
print(torch.matmul(x, y).shape)

torch.Size([2, 3, 4, 4])


In [36]:
x = torch.rand(2, 3, 4, 5)
y = torch.rand(1, 5, 4)
print(torch.matmul(x, y).shape)

torch.Size([2, 3, 4, 4])


### 幂运算: torch.pow(), **


In [52]:
x = torch.tensor([2, 3, 4, 5])
x**2

tensor([ 4,  9, 16, 25])

In [53]:
torch.pow(x,2)

tensor([ 4,  9, 16, 25])

In [54]:
print(x.pow(2))  
print(x)         # 前述运算都不会改变x的值
  

tensor([ 4,  9, 16, 25])
tensor([2, 3, 4, 5])
tensor([ 4,  9, 16, 25])
tensor([ 4,  9, 16, 25])


inplace操作符：原操作符后跟_，例如add_,pow_等

In [55]:
print(x.pow_(2)) #改变x的值
print(x)

tensor([ 16,  81, 256, 625])
tensor([ 16,  81, 256, 625])


### 除法：torch.div(), /

In [58]:
x = torch.rand(2, 3, 4, 5)
y = torch.rand(2, 3, 4, 5)
print((x/y).shape)
print(torch.div(x, y).shape)

torch.Size([2, 3, 4, 5])
torch.Size([2, 3, 4, 5])


### 指数运算
$y_i=e^{(x_i)}$ `torch.exp(tensor, out=None)`    

$y_i=e^{(x_i)} -1$ `torch.expm1(tensor, out=None)`   

In [59]:
x = torch.eye(3)
torch.exp(x)

tensor([[2.7183, 1.0000, 1.0000],
        [1.0000, 2.7183, 1.0000],
        [1.0000, 1.0000, 2.7183]])

In [62]:
torch.expm1(x)

tensor([[1.7183, 0.0000, 0.0000],
        [0.0000, 1.7183, 0.0000],
        [0.0000, 0.0000, 1.7183]])

### 比较：
`>`------`torch.gt(input, other, out=None)`  input>other

`>=`-----`torch.ge(input, other, out=None)`  input>= other

`<=`-----`torch.le(input, other, out=None)`  input=<other
                                                         
`<`-----`torch.lt(input, other, out=None)`  input<other
                                                    
`==`  `torch.eq(input, other, out=None)`  按成员进行等式操作，相同返回1 (理解为元素比较)
 
`!=`   `torch.ne(input, other, out=None)`  input != other 不等于
                                                         
                                                         
`torch.equal(tensor1, tensor2)` #如果tensor1和tensor2有相同的size和elements，则为true （理解为集合比较）










In [63]:
 torch.eq(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))

tensor([[ True, False],
        [False,  True]])

In [64]:
 torch.equal(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))

False

In [70]:
x = 0.5*torch.tensor([[2, 3, 4, 5],[1,2,3,4]])
x**2

tensor([[1.0000, 2.2500, 4.0000, 6.2500],
        [0.2500, 1.0000, 2.2500, 4.0000]])

In [71]:
torch.pow(x,2)

tensor([[1.0000, 2.2500, 4.0000, 6.2500],
        [0.2500, 1.0000, 2.2500, 4.0000]])

元素幂运算与矩阵幂运算

In [85]:
x=torch.ones((2,2),dtype=torch.float)
x.matrix_power(3)

tensor([[4., 4.],
        [4., 4.]])

In [86]:
x.pow(3)

tensor([[1., 1.],
        [1., 1.]])

In [88]:
torch.tensor([1,2,3,4])**torch.tensor([1,2,3,4])

tensor([  1,   4,  27, 256])

torch.clamp(input, min, max, out=None)

将输入input张量每个元素的范围限制到区间 [min,max]，返回结果到一个新张量。

input (Tensor) – 输入张量
min (Number) – 限制范围下限
max (Number) – 限制范围上限
out (Tensor, optional) – 输出张量

In [90]:
a=torch.randint(low=0,high=10,size=(10,1))
print(a)
a=torch.clamp(a,3,5)
print(a)

tensor([[0],
        [3],
        [6],
        [6],
        [1],
        [6],
        [4],
        [0],
        [2],
        [4]])
tensor([[3],
        [3],
        [5],
        [5],
        [3],
        [5],
        [4],
        [3],
        [3],
        [4]])


## indexing

batch_size = 10
features = 25
x = torch.rand((batch_size, features))









第一个样本的所有特征


In [92]:
print(x[0].shape)  # shape [25], this is same as doing x[0,:]

torch.Size([25])


所有样本的第一个特征

In [93]:
print(x[:, 0].shape)  # shape [10]

torch.Size([10])


第三个样本的第一个至第10个特征

In [95]:
print(x[2, 0:10].shape)  # shape: [10]

torch.Size([10])


给指定元素（特定样本的特定特征）赋值

In [96]:
x[0, 0] = 100

### 花式索引

In [97]:
# Fancy Indexing
x = torch.arange(10)
indices = [2, 5, 8]
print(x[indices])  # x[indices] = [2, 5, 8]

tensor([2, 5, 8])


第二行第五列，以及第一行第一列

In [100]:
x = torch.rand((3, 5))
rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])
print(x[rows, cols])  

tensor([0.7891, 0.5021])


In [ ]:
获取小于2或者大于8的元素

In [102]:
# More advanced indexing
x = torch.arange(10)
print(x[(x < 2) | (x > 8)])  # will be [0, 1, 9]

tensor([0, 1, 9])


获取值为偶数的元素

In [104]:
print(x[x.remainder(2) == 0])  # remainder返回一个新的tensor,包含输入input张量每个元素的除法余数，余数与除数有相同的符号。

tensor([0, 2, 4, 6, 8])


$$
y_i=\left\{\begin{matrix}
 x_i& if \quad x_i>5\\ 
x_{i}^{2} & otherwise
\end{matrix}\right.
$$

In [113]:
# Useful operations for indexing
print(torch.where(x > 5, x, x * 2))  # gives [0, 2, 4, 6, 8, 10, 6, 7, 8, 9], all values x > 5 yield x, else x*2

tensor([0, 2, 4, 6, 8])


元素去重

In [115]:
x = torch.tensor([0, 0, 1, 2, 2, 3, 4]).unique()  # x = [0, 1, 2, 3, 4]
x

tensor([0, 1, 2, 3, 4])

获取维度，一共有几维

In [116]:
print(x.ndimension())  # The number of dimensions, in this case 1. if x.shape is 5x5x5 ndim would be 3


1


获取元素个数

In [117]:
x = torch.arange(10)
print(x.numel())  # The number of elements in x (in this case it's trivial because it's just a vector)

10


### Tensor Reshaping    

In [ ]:
# ============================================================= #
#                        Tensor Reshaping                       #
# ============================================================= #

x = torch.arange(9)

# Let's say we want to reshape it to be 3x3
x_3x3 = x.view(3, 3)

# We can also do (view and reshape are very similar)
# and the differences are in simple terms (I'm no expert at this),
# is that view acts on contiguous tensors meaning if the
# tensor is stored contiguously in memory or not, whereas
# for reshape it doesn't matter because it will copy the
# tensor to make it contiguously stored, which might come
# with some performance loss.
x_3x3 = x.reshape(3, 3)

# If we for example do:
y = x_3x3.t()
print(
    y.is_contiguous()
)  # This will return False and if we try to use view now, it won't work!
# y.view(9) would cause an error, reshape however won't

# This is because in memory it was stored [0, 1, 2, ... 8], whereas now it's [0, 3, 6, 1, 4, 7, 2, 5, 8]
# The jump is no longer 1 in memory for one element jump (matrices are stored as a contiguous block, and
# using pointers to construct these matrices). This is a bit complicated and I need to explore this more
# as well, at least you know it's a problem to be cautious of! A solution is to do the following
print(y.contiguous().view(9))  # Calling .contiguous() before view and it works

# Moving on to another operation, let's say we want to add two tensors dimensions togethor
x1 = torch.rand(2, 5)
x2 = torch.rand(2, 5)
print(torch.cat((x1, x2), dim=0).shape)  # Shape: 4x5
print(torch.cat((x1, x2), dim=1).shape)  # Shape 2x10

# Let's say we want to unroll x1 into one long vector with 10 elements, we can do:
z = x1.view(-1)  # And -1 will unroll everything

# If we instead have an additional dimension and we wish to keep those as is we can do:
batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(
    batch, -1
)  # And z.shape would be 64x10, this is very useful stuff and is used all the time

# Let's say we want to switch x axis so that instead of 64x2x5 we have 64x5x2
# I.e we want dimension 0 to stay, dimension 1 to become dimension 2, dimension 2 to become dimension 1
# Basically you tell permute where you want the new dimensions to be, torch.transpose is a special case
# of permute (why?)
z = x.permute(0, 2, 1)

# Splits x last dimension into chunks of 2 (since 5 is not integer div by 2) the last dimension
# will be smaller, so it will split it into two tensors: 64x2x3 and 64x2x2
z = torch.chunk(x, chunks=2, dim=1)
print(z[0].shape)
print(z[1].shape)

# Let's say we want to add an additional dimension
x = torch.arange(
    10
)  # Shape is [10], let's say we want to add an additional so we have 1x10
print(x.unsqueeze(0).shape)  # 1x10
print(x.unsqueeze(1).shape)  # 10x1

# Let's say we have x which is 1x1x10 and we want to remove a dim so we have 1x10
x = torch.arange(10).unsqueeze(0).unsqueeze(1)

# Perhaps unsurprisingly
z = x.squeeze(1)  # can also do .squeeze(0) both returns 1x10

# That was some essential Tensor operations, hopefully you found it useful!