# tensor初始化、数学操作等

## 初始化
   

### torch.tensor()

使用`torch.tensor()`将numpy或者list等转换为tensor

In [1]:
import torch
import numpy as np
my_tensor=torch.tensor(np.ones(3))
print(my_tensor)

tensor([0., 0., 0.], dtype=torch.float64)


In [4]:
my_tensor=torch.tensor([1,2,3])
my_tensor

tensor([1, 2, 3])

使用多维list初始化多维tensor,例如下述代码初始化一个两行三列的tensor

In [36]:
my_tensor=torch.tensor([[1,2,3],[4, 5, 6]])
print(my_tenosr)
print(my_tenosr.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


通过`dtype`字段指定数据类型，`dtype`可选`torch.float32`, `torch.float64`, `torch.float16`, `torch.int8`, `torch.int16`, `torch.int32`等

例如

In [15]:
my_tensor=torch.tensor([[1,2,3],[4, 5, 6]],dtype=torch.float64)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [18]:
my_tensor=torch.tensor([[1,2,3],[4, 5, 6]],dtype=torch.float32)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [17]:
my_tensor=torch.tensor([[1,2,3],[4, 5, 6]],dtype=torch.int32)
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

通过`device`字段指定将tensor分配分配给哪个设备（cpu或则gpu）。具体来说，`torch.device`代表将`torch.Tensor`分配到的设备的对象。`torch.device`包含一个设备类型（‘cpu’或‘cuda’）和可选的设备序号。如果设备序号不存在，则为当前设备。如：`torch.Tensor`用设备构建`'cuda'`的结果等同于`‘cuda：X’`，其中X是`torch.cuda.current_device()`的结果。

In [23]:
my_tensor=torch.tensor([[1,2,3],[4, 5, 6]],dtype=torch.int32,device='cpu')
print(my_tensor.device)

cpu


可以使用如下代码，优先将tensor分配给GPU

In [25]:
mydevice='cuda' if torch.cuda.is_available() else 'cpu'
print(mydevice)

cpu


In [30]:
my_tensor=torch.tensor([1,2,3],device=mydevice)
print(my_tensor.device)
print(my_tensor.dtype)

cpu
torch.int64


通过字段'requires_grad'来指定tensor是否需要进行求导（反向传播），默认情况下该字段为`False`

In [38]:
print(my_tensor.requires_grad)

False


In [39]:
my_tensor=torch.tensor([1.5,2,3],requires_grad=True)
print(my_tensor.requires_grad)

True


如果想改变`requires_grad`这个属性，可以调用`tensor.requires_grad_()`方法：
```
x.requires_grad_(True)
```

In [40]:
my_tensor=torch.tensor([1.5,2,3])
print(my_tensor.requires_grad)
my_tensor.requires_grad_(True)
print(my_tensor.requires_grad)

False
True


### 填充指定size的tensor
1. torch.empty()  
2. torch.ones()
3. torch.zeros()  
4. torch.eye()

#### 1. torch.empty()

使用`torch.empty()`可以创建包含未初始化数据的张量
标量值0填充的张量,其形状由变量参数size定义

In [47]:
my_tensor=torch.empty((3,4))
print(my_tensor.shape)
print(my_tensor)#具体值实际上待定，不要以为是初始化为0

torch.Size([3, 4])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
#### 2. torch.zeros()

In [70]:
my_tensor=torch.zeros(3,4)
print(my_tensor.shape)
print(my_tensor)

torch.Size([3, 4])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


#### 3. torch.ones()

In [69]:
my_tensor=torch.ones(3,4,5)
print(my_tensor.shape)
print(my_tensor)

torch.Size([3, 4, 5])
tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])


#### 4. torch.eye()  
生成对角线全1，其余部分全0的二维数组

In [63]:
my_tensor=torch.eye(3)
print(my_tensor.shape)
print(my_tensor)

torch.Size([3, 3])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [64]:
my_tensor=torch.eye(2,3)
print(my_tensor.shape)
print(my_tensor)

torch.Size([2, 3])
tensor([[1., 0., 0.],
        [0., 1., 0.]])


#### 4. torch.rand()  
包含了从区间[0, 1)的均匀分布中抽取的一组随机数

In [68]:
my_tensor=torch.rand(3,4)
print(my_tensor.shape)
print(my_tensor)

torch.Size([3, 4])
tensor([[0.4518, 0.6142, 0.7612, 0.3828],
        [0.6862, 0.0493, 0.5492, 0.2327],
        [0.7688, 0.1837, 0.6124, 0.3847]])


#### 4. torch.randn()  
包含了从**标准正态分布**中抽取的一组随机数

In [67]:
my_tensor=torch.randn(3,4)
print(my_tensor.shape)
print(my_tensor)

torch.Size([3, 4])
tensor([[ 0.0647, -0.1434,  2.0323, -0.2759],
        [-0.9258,  0.3505, -0.7455, -0.0367],
        [ 0.6792,  0.5661,  1.5247, -1.3066]])


#### torch.arange( start, end, step)：不含end (建议使用)
#### torch.range( start, end, step): 含end (不建议使用，后续可能会被移除)

In [82]:
my_tensor = torch.arange(start=0, end=5, step=1)  
print(my_tensor.shape)
print(my_tensor)
my_tensor = torch.range(start=0, end=5, step=1)  
print(my_tensor.shape)
print(my_tensor)

torch.Size([5])
tensor([0, 1, 2, 3, 4])
torch.Size([6])
tensor([0., 1., 2., 3., 4., 5.])


<ipython-input-82-c200653eb586>:4: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  my_tensor = torch.range(start=0, end=5, step=1)


也可以不用加start和end关键字，按参数次序写即可

In [88]:
my_tensor = torch.arange(0,5,2)  
print(my_tensor.shape)
print(my_tensor)
my_tensor = torch.range(0,5,2)  
print(my_tensor.shape)
print(my_tensor)

torch.Size([3])
tensor([0, 2, 4])
torch.Size([3])
tensor([0., 2., 4.])


<ipython-input-88-1464d512cadc>:4: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  my_tensor = torch.range(0,5,2)


step参数默认为1

In [84]:
my_tensor = torch.arange(0,5)  
print(my_tensor.shape)
print(my_tensor)
my_tensor = torch.range(0,5) #注意，结果中包含end 
print(my_tensor.shape)
print(my_tensor)

torch.Size([5])
tensor([0, 1, 2, 3, 4])
torch.Size([6])
tensor([0., 1., 2., 3., 4., 5.])


<ipython-input-84-5b1a9771b9c9>:4: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  my_tensor = torch.range(0,5)


也可以只传入end参数，此时默认start为0

In [80]:
my_tensor = torch.arange( ,11,2)  
print(my_tensor.shape)
print(my_tensor)

SyntaxError: invalid syntax (<ipython-input-80-15233ef67f78>, line 1)

In [87]:
my_tensor = torch.arange(5)  
print(my_tensor.shape)
print(my_tensor)
my_tensor = torch.range(0,5)  
print(my_tensor.shape)
print(my_tensor)

torch.Size([5])
tensor([0, 1, 2, 3, 4])
torch.Size([6])
tensor([0., 1., 2., 3., 4., 5.])


<ipython-input-87-1bff08bca9ba>:4: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  my_tensor = torch.range(0,5)


In [ ]:
x = torch.linspace(start=0.1, end=1, steps=10)  # x = [0.1, 0.2, ..., 1]

#### torch.linspace(start, end, steps)
`torch.linspace`同`torch.range`均是左闭右闭，即返回值中既包含start也包含end. 但是不同之处在于，`torch.linspace`中的steps参数应该理解为元素总个数，而`torch.range`中的step参数应该理解为步长（前后元素之间的差）
这个张量包含了从start到end（包括端点）的等距的steps个数据点

In [89]:
my_tensor = torch.range(0,5,2)  
print(my_tensor.shape)
print(my_tensor)
my_tensor = torch.linspace(0,5,2)  
print(my_tensor.shape)
print(my_tensor)

torch.Size([3])
tensor([0., 2., 4.])
torch.Size([2])
tensor([0., 5.])


<ipython-input-89-1f46291fd614>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  my_tensor = torch.range(0,5,2)


#### torch.diag(input, diagonal=0, out=None) → Tensor
如果输入是一个向量(1D 张量)，则返回一个以input为对角线元素的2D方阵
如果输入是一个矩阵(2D 张量)，则返回一个包含input对角线元素的1D张量

参数diagonal指定对角线:
diagonal = 0, 主对角线
diagonal > 0, 主对角线之上
diagonal < 0, 主对角线之下
————————————————

In [93]:
my_tensor = torch.ones(3,3)
print(torch.diag(my_tensor))#主对角线
print(torch.diag(my_tensor).shape)

tensor([1., 1., 1.])
torch.Size([3])


In [94]:
print(torch.diag(my_tensor,1)) #主对角线之上的第一条对角线
print(torch.diag(my_tensor).shape)

tensor([1., 1.])
torch.Size([3])


In [95]:
print(torch.diag(my_tensor,2)) #主对角线之上的第二条对角线
print(torch.diag(my_tensor).shape)

tensor([])
torch.Size([3])


In [96]:
print(torch.diag(my_tensor,-2)) #主对角线之下的第二条对角线
print(torch.diag(my_tensor).shape)

tensor([1.])
torch.Size([3])


In [97]:
print(torch.diag(my_tensor,3)) #主对角线之上的第三条对角线（无元素）
print(torch.diag(my_tensor).shape)

tensor([])
torch.Size([3])


转换数值类型(int, float, double)等

In [105]:
my_tensor = torch.tensor([-2,-1,0,1,2])
my_tensor

tensor([-2, -1,  0,  1,  2])

转换为布尔类型（将非0值转为True）

In [108]:
print(f"Converted Boolean: {my_tensor.bool()}")  # Converted to Boolean: 1 if nonzero


Converted Boolean: tensor([ True,  True, False,  True,  True])
Converted int16 tensor([-2, -1,  0,  1,  2], dtype=torch.int16)
Converted int64 tensor([-2, -1,  0,  1,  2])
Converted float16 tensor([-2., -1.,  0.,  1.,  2.], dtype=torch.float16)
Converted float32 tensor([-2., -1.,  0.,  1.,  2.])
Converted float64 tensor([-2., -1.,  0.,  1.,  2.], dtype=torch.float64)


转换为int16

In [109]:
print(f"Converted int16 {my_tensor.short()}")  # Converted to int16

Converted int16 tensor([-2, -1,  0,  1,  2], dtype=torch.int16)


转换为int64

In [110]:
print(
    f"Converted int64 {my_tensor.long()}"
)  # Converted to int64 (This one is very important, used super often)

Converted int64 tensor([-2, -1,  0,  1,  2])


转换为float16

In [111]:
print(f"Converted float16 {my_tensor.half()}")  # Converted to float16


Converted float16 tensor([-2., -1.,  0.,  1.,  2.], dtype=torch.float16)


转换为float32

In [112]:
print(
    f"Converted float32 {my_tensor.float()}"
)  # Converted to float32 (This one is very important, used super often)


Converted float32 tensor([-2., -1.,  0.,  1.,  2.])


转换为float64

In [113]:
print(f"Converted float64 {my_tensor.double()}")  # Converted to float64

Converted float64 tensor([-2., -1.,  0.,  1.,  2.], dtype=torch.float64)


##### torch.from_numpy()与torch.numpy()
前者将numpy类型转换为tensor，后者将tensor转换为numpy类型

In [116]:
np_array = np.zeros((5, 5))
my_tensor = torch.from_numpy(np_array)
np_array_again = (
    my_tensor.numpy()
)  # np_array_again will be same as np_array (perhaps with numerical round offs)
print(my_tensor)
print(np_array_again)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
